---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
      enabled: true
      exclude_fingerprints:
      - 167bb9772249e42d4f262dd4af72b620
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/
- docs/
