---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
      enabled: true
      exclude_fingerprints:
      - 6712dc780f17ef0aef1d502570c70e9a
      - 47780d290927676fd7d239782fe329ed
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/
- docs/
- vapor/
- figures/
- images/
- "**.json"
- "**.md"
- "**.txt"
- "**.xml"
